# Site settings
title: Teh Lemon
email: tehlemon@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  
url:  https://tehlemon.com
twitter_username: tehlemon
github_username:  Teh-Lemon
favicon:     "img/favicon.ico"

# Build settings
markdown: kramdown
highlighter: rouge

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/

